#ifndef APP_GEN_CTX_H
#define APP_GEN_CTX_H

#include <stdint.h>

/*
 * Small fixed-size sliding context buffer shared by every generation
 * app (gen_from_checkpoint, gen_moe_checkpoint, gen_moe_expert0, ...).
 * Was previously copy-pasted verbatim into each app source file; now
 * it's one header. `cap` is passed in so callers can still use
 * whatever context length matches their model's CTX.
 */
static inline void gen_ctx_append(uint8_t *ctx, int cap, int *len, uint8_t b) {
    if (*len < cap) {
        ctx[*len] = b;
        (*len)++;
        return;
    }
    for (int i = 1; i < cap; ++i) ctx[i - 1] = ctx[i];
    ctx[cap - 1] = b;
}

/* Maps a generated byte to something safe to print: newline stays a
 * newline, anything outside printable ASCII becomes '.'. */
static inline int gen_ctx_printable(int b) {
    if (b == '\n' || (b >= 32 && b <= 126)) return b;
    return '.';
}

#endif
